### ISSUE TITLE
Issue with deploy_mrp_app.sh - File skipped during release.

### ISSUE THREAD

**Issue by techbunny** [Microsoft/PartsUnlimitedMRP#77] opened 2016-09-01 18:43 UTC
I've been running into the following release errors with during the hosted CD lab.  I've double-checked the lab steps and the prior build lab reports success.  

2016-09-01T18:18:44.1457580Z Store key in cache? (y/n) dos2unix: deploy_mrp_app.sh: No such file or directory
2016-09-01T18:18:44.1457580Z dos2unix: Skipping deploy_mrp_app.sh, not a regular file.
2016-09-01T18:18:44.1497560Z bash: ./deploy_mrp_app.sh: No such file or directory
2016-09-01T18:18:44.4241136Z ##[error]Process completed with exit code 127.

**Comment by julienstroheker** [comment] 2016-09-01 19:14
Hi @techbunny 

Thanks for your feedback, let me check on my side if I can reproduce your error.

I'll keep you in touch.

Thanks

**Comment by julienstroheker** [comment] 2016-09-01 20:03
Seems everything is working on my side.

Can you check in your last build, on the artifacts tab, if you can see the deploy folder : 

![capture d ecran 2016-09-01 a 15 53 51](https://cloud.githubusercontent.com/assets/8661347/18182284/51269a92-705d-11e6-810d-492cdb2858ba.png)

Click on Explore, and tell me if you can see the sh script like this : 

![capture d ecran 2016-09-01 a 16 02 18](https://cloud.githubusercontent.com/assets/8661347/18182336/8e56ca54-705d-11e6-829a-ae2796a49a74.png)

Thanks

**Comment by techbunny** [comment] 2016-09-01 22:19
The artifacts folder does have what's expected during the build process, however the failure occurs during the release.

**Comment by julienstroheker** [comment] 2016-09-02 15:10
Yes, you release fail because you don't have the artifacts expected inside the deploy folder. 
Can you double check, inside your build definition, this step, and make sure that you have this correct three lines inside the Contents section : 

**11.** Select the second Publish Build Artifacts task, and fill in the input values with the following:
```
Copy Root: $(Build.SourcesDirectory)
Contents: 
  **/deploy/SSH-MRP-Artifacts.ps1
  **/deploy/deploy_mrp_app.sh
  **/deploy/MongoRecords.js
Artifact Name: deploy
Artifact Type: Server
```
![](<https://github.com/Microsoft/PartsUnlimitedMRP/blob/master/docs/HOL_Continuous-Integration/media/second_copy_publish.png?raw=true>)

Thanks a lot.

**Comment by julienstroheker** [comment] 2016-09-06 15:17
Any news @techbunny ?

Thanks

**Comment by julienstroheker** [comment] 2016-09-07 05:44
Lets close the issue for now, we can continue to talk about it here and in case re open it.

Thanks

**Closed by julienstroheker** 2016-09-07 05:44 UTC
